export * from './admin.service';
import { AdminService } from './admin.service';
export * from './class.service';
import { ClassService } from './class.service';
export * from './device.service';
import { DeviceService } from './device.service';
export * from './form.service';
import { FormService } from './form.service';
export * from './menu.service';
import { MenuService } from './menu.service';
export * from './notice.service';
import { NoticeService } from './notice.service';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './parent.service';
import { ParentService } from './parent.service';
export * from './statistic.service';
import { StatisticService } from './statistic.service';
export * from './student.service';
import { StudentService } from './student.service';
export * from './teacher.service';
import { TeacherService } from './teacher.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AdminService, ClassService, DeviceService, FormService, MenuService, NoticeService, NotificationService, ParentService, StatisticService, StudentService, TeacherService, UserService];
