/**
 * Demo App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Activity { 
    id?: number;
    type?: number;
    classID?: number;
    dateOccur?: string;
    dateExpired?: string;
    teacherID?: number;
    title?: string;
    content?: string;
    photo1?: string;
    caption1?: string;
    photo2?: string;
    caption2?: string;
    photo3?: string;
    caption3?: string;
    photo4?: string;
    caption4?: string;
    photo5?: string;
    caption5?: string;
    dateCreated?: string;
}
