/**
 * Demo App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *  the object contains the class statistic
 */
export interface AdminStatistic { 
    id?: number;
    classID?: number;
    /**
     * the total of student
     */
    totalStudents?: number;
    /**
     * Nghi khong phep
     */
    absences?: number;
    /**
     * Nghi co phep
     */
    requestedAbsences?: number;
    morningMeals?: number;
    noonMeals?: number;
    afternoonMeals?: number;
    lateMeals?: number;
    latePickup?: number;
    dateCreated?: string;
}
