/**
 * Demo App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * the application for the parent to fill up. including absence, meal cancel, late pickup application
 */
export interface ApplicationForm { 
    id?: number;
    /**
     * type: 1- nghi hoc, 2- don tre, 3- huy bua
     */
    type?: number;
    studentID?: number;
    posterID?: number;
    pickerName?: string;
    pickerPhone?: string;
    pickerPhoto?: string;
    /**
     * class: 1- sang, 2- chieu, 3-ca ngay
     */
    classTime?: string;
    title?: string;
    content?: string;
    dateRequest?: Date;
    timeRequest?: Date;
    /**
     * Meal: 1- sang, 2- chieu, 3-xe, 4-ca ngay
     */
    cancelMeal?: number;
    isCancelMeal?: boolean;
    lateMeal?: boolean;
    dateCreated?: string;
}
