/**
 * Demo App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NotificationData { 
    id?: number;
    priority?: number;
    /**
     * 1-parent, 2-teacher
     */
    type?: number;
    /**
     * 1-hoc phi, 2- thong bao chung
     */
    category?: number;
    /**
     * target of the notification
     */
    classID?: number;
    title?: string;
    content?: string;
    posterID?: number;
    seenCount?: number;
    dateCreated?: string;
    dateExpired?: Date;
}
