/**
 * Demo App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Notice { 
    id?: number;
    type?: number;
    dateOccur?: Date;
    content?: Array<string>;
    confirmMessage?: string;
    studentID?: number;
    parentID?: number;
    teacherID?: number;
    dateCreated?: string;
    dateExpired?: string;
}
