/**
 * Demo App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Parent { 
    id?: number;
    userID?: number;
    name?: string;
    email?: string;
    loginName?: string;
    address?: string;
    addressCity?: string;
    addressDistrict?: string;
    addressStreet?: string;
    phone?: string;
    photo?: string;
    status?: number;
    dateCreated?: string;
}
