/**
 * Demo App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Student { 
    id?: number;
    classID?: number;
    parentID?: number;
    name?: string;
    birthday?: Date;
    phone?: string;
    /**
     * User Status: 1- presence, 0- absence, 2- requested, 3- unrequested
     */
    studentStatus?: number;
}
