/**
 * Demo App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TuitionPayment { 
    id?: number;
    year?: number;
    quarter?: number;
    studentID?: number;
    paid?: number;
    datePaid?: string;
    dateNotice?: string;
    dateSeen?: string;
    noticeCount?: number;
    note?: string;
    amount?: string;
    dateCreated?: string;
}
