/**
 * Demo App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *  the student tuition fee
 */
export interface TuitionFee { 
    id?: number;
    quater?: number;
    paid?: boolean;
    classID?: number;
    studentID?: number;
    total?: number;
    tuition?: number;
    food?: number;
    bus?: number;
    refund?: number;
    other?: number;
    dateCreated?: string;
}
