/**
 * Demo App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *  the user object of the system
 */
export interface User { 
    id?: number;
    username?: string;
    name?: string;
    email?: string;
    password?: string;
    phone?: string;
    /**
     * User Role: 3- admin, 2- teacher, 1- parent
     */
    role?: number;
    /**
     * User Status: 1- active, 2- inactive
     */
    userStatus?: number;
}
